goodreads:
  urls:
    books: "https://www.goodreads.com/list/show/1.Best_Books_Ever"
    book_details: "https://www.goodreads.com/book/show/{book_id}/"


  selectors:
    book_title: 'h1[data-testid="bookTitle"]'
    genre: "span.BookPageMetadataSection__genreButton"
    author: "span.ContributorLink__name"
    rating: "div.RatingStatistics__rating"
    rating_meta: "div.RatingStatistics__meta"
    show_more: "//button[@aria-label='Show all items in the list']"
    tag_p: "p"
    book_link: "a.bookTitle"

  headers:
    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"

  output:
    fieldnames:
      - title
      - author
      - rating
      - genres
      - pages
      - ratings_count
    csv_path: "data/db.csv"
